### PR TITLE
Add wiremock

### PR DESCRIPTION
**Pull request by flomillot**
Signed-off-by: Florent MILLOT <millotflo@gmail.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Dependencies update

### CODE REVIEW

**Comment by flomillot** [comment]
@SlimaneAmar is it still relevant ?

**Comment by SlimaneAmar** [comment]
Yes

**Comment by flomillot** [comment]
@SlimaneAmar Can you validate and then I merge it ?

**Review by SlimaneAmar — APPROVED** [review]

**Comment by flomillot** [comment]
Thanks

**Pull request merged**
